### ISSUE TITLE
[Feature] Ajouter les Note-Alerte-Information  (admonition)

### ISSUE THREAD

**Issue by guiguid** [pluxml/PluCSS#16]
Bonjour serait-il possible d'ajouter les "admonition".
Le site de Pluxml lui-même les utilises dans la partie "DOC" : https://wiki.pluxml.org/installer/installation/
![image](https://user-images.githubusercontent.com/71406/80359452-236fae80-887e-11ea-9b91-9468b7907f94.png)

depuis base.css du site PluXML.
```css
.admonition {
    padding: 15px;
    margin-bottom: 20px;
    border: 1px solid transparent;
    border-radius: 4px;
    text-align: left;
}

.admonition.note { /* csslint allow: adjoining-classes */
    color: #3a87ad;
    background-color: #d9edf7;
    border-color: #bce8f1;
}

.admonition.warning { /* csslint allow: adjoining-classes */
    color: #c09853;
    background-color: #fcf8e3;
    border-color: #fbeed5;
}

.admonition.danger { /* csslint allow: adjoining-classes */
    color: #b94a48;
    background-color: #f2dede;
    border-color: #eed3d7;
}

.admonition-title {
    font-weight: bold;
    text-align: left;
}
```
